name: TitlePlugin
version: '${project.version}'
main: ideamc.titleplugin.TitlePlugin
api-version: '1.13'
folia-supported: true
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
authors:
  - suxiaolin
  - xiantiao
commands:
  tip:
    description: 'player command of TitlePlugin'
    usage: '/tip'
    permission: 'titleplugin.player'
    permission-message: 'You do not have permission to use this command.'
  atip:
    description: 'op command of TitlePlugin'
    usage: '/atip'
    permission: 'titleplugin.op'
    permission-message: 'You do not have permission to use this command.'
    default: op

